### ISSUE TITLE
Multi region support

### ISSUE THREAD

**Issue by Halama** [keboola/curated-data-extractor#2]
Now it allows to fetch data only from project in US KBC https://github.com/keboola/curated-data-extractor/blob/6b3660e60799dff4e4b2f6d3fa8e39309b6f2685/src/Keboola/CuratedDataExtractor/Executor.php#L62 . It should support other regions.
And we should duplicate Shared data project to EU region.

**Comment by odinuv** [comment]
fixed in 1653f793b1cb6a10444ca27818c2600cba86d505
