### ISSUE TITLE
Add UAH to currency list

### ISSUE THREAD

**Issue by yustme** [keboola/curated-data-extractor#7]
Máme tady request na přidání Ukrajinské Hřivny -> https://keboola.zendesk.com/agent/tickets/10677

The exchange rate can be obtained by the following request: 
`http://data.fixer.io/api/2019-05-28?access_key={API_KEY}&base=EUR&format=1`

**Comment by romanbracinik** [comment]
- Upraviť transformácie v projekte 452 (Transpone EUR, USD, GBP) tak aby sa pridala aj nová mena ktora je potrebná.
- Pridať do dokumentácie podporu novej currency https://github.com/keboola/connection-docs
- Upraviť na https://components.keboola.com podporu novej currency v long description.
